### ISSUE TITLE
Supporting JEDI_GDAS: verify GNSSRO GSI ncdiag files in UFO

### ISSUE THREAD

**Issue by hailingz** [JCSDA-internal/GSI#15]
Related issues:

1. GSI GNSSRO code changes were merged to jeda_gdas 
https://github.com/JCSDA-internal/GSI/pull/7

2. An IODA converter was used to convert GSI ncdiag files to IODA observation file and geoval file.
https://github.com/JCSDA-internal/ioda-converters/pull/555

This issue is verifying the files generated by 1) and 2) in UFO. 

@huishao-r @fcvdb @CoryMartin-NOAA

**Comment by hailingz** [comment]
This shows the UFO verification. What I did includes, 
1) converts Cory's GSI ncdiag file  diag_conv_gps_ges.2020121500.nc4 using the IODA converter https://github.com/JCSDA-internal/ioda-converters/blob/feature/gnssro_gsi2ioda/src/gnssro/gnssro_bufr2ioda.f90
2) run UFO test 
3) plot bending_angle@GsiHofX and bending_angle@hofx

please close this issue and review the ioda converter if you verify this result. Thanks!
https://github.com/JCSDA-internal/ioda-converters/pull/555
@huishao-r @fcvdb @CoryMartin-NOAA


![gsihofx_jedi_2020121500_jedi_gdas](https://user-images.githubusercontent.com/36716145/119177292-5bb5d200-ba29-11eb-8806-1711f8aeb585.png)

**Comment by fcvdb** [comment]
@hailingz The `gnssro_bufr2ioda.f90` is for BUFR conversion, do you mean `gnssro gsi2ioda.f90`?

**Comment by hailingz** [comment]
> @hailingz The `gnssro_bufr2ioda.f90` is for BUFR conversion, do you mean `gnssro gsi2ioda.f90`?

Thank you for catching that! Changed!

**Comment by hailingz** [comment]
done!
